dist: xenial

services:
  - postgresql

language: python

cache: pip

sudo: true

addons:
  chrome: stable

matrix:
  fast_finish: true
  include:
#  - env: TOX_ENV=py27-django18
#    python: 2.7
#  - env: TOX_ENV=py35-django18
#    python: 3.5
#  - env: TOX_ENV=py36-django18
#    python: 3.6

#  - env: TOX_ENV=py27-django111
#    python: 2.7
  - env: TOX_ENV=py35-django111
    python: 3.5
  - env: TOX_ENV=py36-django111
    python: 3.6

#  - env: TOX_ENV=py35-django20
#    python: 3.5
  - env: TOX_ENV=py36-django20
    python: 3.6
  - env: TOX_ENV=py37-django22
    python: 3.7

  - env: TOX_ENV=py36-django21
    python: 3.6
  - env: TOX_ENV=py37-django21
    python: 3.7

  - env: TOX_ENV=py36-django22
    python: 3.6
  - env: TOX_ENV=py37-django22
    python: 3.7

  - env: TOX_ENV=py36-django30
    python: 3.6
  - env: TOX_ENV=py37-django30
    python: 3.7

before_install:
  - sudo apt-get install -y xvfb libappindicator1 fonts-liberation
#  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
#  - sudo dpkg -i google-chrome*.deb
#  - wget http://ftp.us.debian.org/debian/pool/main/c/chromium/chromium_75.0.3770.90-1_amd64.deb
#  - sudo dpkg -i chromium_75.0.3770.90-1_amd64.deb

install:
  - wget http://chromedriver.storage.googleapis.com/75.0.3770.90/chromedriver_linux64.zip
#  - wget http://chromedriver.storage.googleapis.com/74.0.3729.6/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/
  - pip install -r examples/requirements/test.txt

before_script:
  - export CHROME_BIN=/home/travis/chromedriver
  - psql -c 'create database fobi_test;' -U postgres
  - sleep 2

script: travis_retry tox -e $TOX_ENV
